# Register
POST http://localhost:9980/register
Content-Type: application/json

{
  "username": "Вася4",
  "password": "dgwgwrgeg"
}

###

# Login
POST http://localhost:9980/login
Content-Type: application/x-www-form-urlencoded

username=Вася4&password=dgwgwrgeg

###
###

# Squeeze link
POST http://localhost:9980/squeeze
authorization: Bearer d55759c2-3ebe-484a-9cc5-bb6c17342f8d
Content-Type: application/json

{
  "link": "https://ya.ru/dgt66666"
}

###


###

# Go to squeezed link
GET http://localhost:9980/s/8fec6

###

# Get statistics
GET http://localhost:9980/statistics?offset=0&limit=10&sort=asc
Authorization: Bearer 019637ca-684b-4c80-8e58-1e20b2a02dc1

###

